### ISSUE TITLE
Getting ImportError on Ubuntu 16.04.2

### ISSUE THREAD

**Issue by kmbasad** [cosmo-ethz/hide#2]
I found Hide&Seek really interesting because I can use it to simulate MeerKAT single dish observations for HI intensity mapping at lower redshifts. I would also like to contribute in the future by building new features into HIDE relevant for MeerKAT surveys.

Now, the problem I am getting is: after installing hide in "develop" mode, and running this:
$ hide --strategy-start=2016-03-21-00:00:00 --strategy-end=2016-03-21-23:59:00 --verbose=True hide.config.bleien7m

I get:

Processing 2016-03-21 00:00:00
Traceback (most recent call last):
  File "/home/asad/anaconda2/bin/hide", line 11, in <module>
    load_entry_point('hide==0.1.0', 'console_scripts', 'hide')()
  File "/home/asad/anaconda2/lib/python2.7/site-packages/ivy/cli/main.py", line 28, in run
    _main(*sys.argv[1:])
  File "/home/asad/anaconda2/lib/python2.7/site-packages/ivy/cli/main.py", line 37, in _main
    mgr.launch()
  File "/home/asad/anaconda2/lib/python2.7/site-packages/ivy/workflow_manager.py", line 107, in launch
    executor.run(ctx().params.plugins)
  File "/home/asad/anaconda2/lib/python2.7/site-packages/ivy/backend.py", line 48, in run
    return map(LoopWrapper(loop), mapPlugin.getWorkload())
  File "/home/asad/anaconda2/lib/python2.7/site-packages/ivy/backend.py", line 129, in __call__
    plugin()
  File "/home/asad/anaconda2/lib/python2.7/site-packages/ivy/plugin/parallel_plugin_collection.py", line 81, in __call__
    ctxList = backendImpl.run(self.pluginList, mapPlugin)
  File "/home/asad/anaconda2/lib/python2.7/site-packages/ivy/backend.py", line 48, in run
    return map(LoopWrapper(loop), mapPlugin.getWorkload())
  File "/home/asad/anaconda2/lib/python2.7/site-packages/ivy/backend.py", line 129, in __call__
    plugin()
  File "/home/asad/Dropbox/Postdoc/khan/scripts/hide/hide/plugins/qu_opt_coord_transform.py", line 43, in __call__
    tree = sphere.ArcKDTree(thetas, phis)
  File "/home/asad/Dropbox/Postdoc/khan/scripts/hide/hide/utils/sphere.py", line 84, in __init__
    self.tree = spatial.cKDTree(dir2vec(theta, phi))
  File "/home/asad/Dropbox/Postdoc/khan/scripts/hide/hide/utils/sphere.py", line 57, in dir2vec
    sin_t, cos_t = sin_cos(theta) #sin(theta), cos(theta)
  File "/home/asad/Dropbox/Postdoc/khan/scripts/hide/hide/utils/__init__.py", line 47, in sin_cos
    _sin_cos_hope(x, len(x), y, int(_TABLERANGE), _SINTABLE, _COSTABLE)
  File "/home/asad/anaconda2/lib/python2.7/site-packages/hope/_wrapper.py", line 71, in _hope_callback
    return self(*args) if self.cache is None else self.cache(*args)
  File "/home/asad/anaconda2/lib/python2.7/site-packages/hope/_wrapper.py", line 115, in __call__
    module = __import__(localfilename, globals(), locals(), [], -1)
ImportError: /home/asad/.hope/_sin_cos_hope_f239b2551edd3ed4b7e0fa9ae0c761de059e252837877c1409a3c1cc_0.so: undefined symbol: _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE

**Comment by kmbasad** [comment]
I have now understood that this was due to a conflict between my default python and the anaconda python. Trying to resolve the issue but no luck yet.

**Comment by kmbasad** [comment]
Worked after removing anaconda and reinstalling. Thanks.

**Comment by jakeret** [comment]
Glad you could resolve the issue by yourself.
Anyway, if you get some issues in the future that are related to the `JIT HOPE` package, it *might* help to delete the `.hope` folder to retrigger a recompilation
