### ISSUE TITLE
UnsupportedPluginTypeException

### ISSUE THREAD

**Issue by zhangasia** [cosmo-ethz/hide#6]
When I run the command
```
hide --strategy-start=2016-03-21-00:00:00 --strategy-end=2016-03-21-23:59:00 --verbose=True hide.config.bleien7m
```
**There was an error，**
```
Traceback (most recent call last):
  File "/home/zhangyazhou/.local/bin/hide", line 11, in <module>
    load_entry_point('hide==0.1.0', 'console_scripts', 'hide')()
  File "/home/zhangyazhou/anaconda3/envs/hide_env/lib/python2.7/site-packages/ivy/cli/main.py", line 28, in run
    _main(*sys.argv[1:])
  File "/home/zhangyazhou/anaconda3/envs/hide_env/lib/python2.7/site-packages/ivy/cli/main.py", line 37, in _main
    mgr.launch()
  File "/home/zhangyazhou/anaconda3/envs/hide_env/lib/python2.7/site-packages/ivy/workflow_manager.py", line 107, in launch
    executor.run(ctx().params.plugins)
  File "/home/zhangyazhou/anaconda3/envs/hide_env/lib/python2.7/site-packages/ivy/backend.py", line 48, in run
    return map(LoopWrapper(loop), mapPlugin.getWorkload())
  File "/home/zhangyazhou/anaconda3/envs/hide_env/lib/python2.7/site-packages/ivy/backend.py", line 126, in __call__
    for plugin in self.loop:
  File "/home/zhangyazhou/anaconda3/envs/hide_env/lib/python2.7/site-packages/ivy/loop.py", line 95, in next
    return self._instantiate(plugin)
  File "/home/zhangyazhou/anaconda3/envs/hide_env/lib/python2.7/site-packages/ivy/loop.py", line 136, in _instantiate
    return PluginFactory.createInstance(pluginName, self.ctx)
  File "/home/zhangyazhou/anaconda3/envs/hide_env/lib/python2.7/site-packages/ivy/plugin/plugin_factory.py", line 59, in createInstance
    raise UnsupportedPluginTypeException("Module '%s' could not be instantiated'" % pluginName, ex)ivy.exceptions.exceptions.UnsupportedPluginTypeException: (u"Module 'hide.plugins.load_beam_profile' could not be instantiated'", ValueError(u"Coordinate frame barycentricmeanecliptic not in allowed values ['altaz', 'barycentrictrueecliptic', 'cirs', 'fk4', 'fk4noeterms', 'fk5', 'galactic', 'galacticlsr', 'galactocentric', 'gcrs', 'geocentrictrueecliptic', 'hcrs', 'heliocentrictrueecliptic', 'icrs', 'itrs', 'lsr', 'precessedgeocentric', 'supergalactic']",))
```
* My operating system is the virtual machine ubuntu20
Thank you a lot

**Comment by AndrewDao11** [comment]
I also encountered the same problem, and hope someone can give advice

Traceback (most recent call last):  File "/home/dao/.local/bin/hide", line 11, in <module>    load_entry_point('hide==0.1.0', 'console_scripts', 'hide')()
  File "/opt/software/anaconda3/envs/py27/lib/python2.7/site-packages/ivy/cli/main.py", line 28, in run    _main(*sys.argv[1:])  File "/opt/software/anaconda3/envs/py27/lib/python2.7/site-packages/ivy/cli/main.py", line 37, in _main
    mgr.launch()
  File "/opt/software/anaconda3/envs/py27/lib/python2.7/site-packages/ivy/workflow_manager.py", line 107, in launch
    executor.run(ctx().params.plugins)
  File "/opt/software/anaconda3/envs/py27/lib/python2.7/site-packages/ivy/backend.py", line 48, in run
    return map(LoopWrapper(loop), mapPlugin.getWorkload())
  File "/opt/software/anaconda3/envs/py27/lib/python2.7/site-packages/ivy/backend.py", line 126, in __call__    for plugin in self.loop:
  File "/opt/software/anaconda3/envs/py27/lib/python2.7/site-packages/ivy/loop.py", line 95, in next
    return self._instantiate(plugin)
  File "/opt/software/anaconda3/envs/py27/lib/python2.7/site-packages/ivy/loop.py", line 136, in _instantiate
    return PluginFactory.createInstance(pluginName, self.ctx)
  File "/opt/software/anaconda3/envs/py27/lib/python2.7/site-packages/ivy/plugin/plugin_factory.py", line 59, in createInstance
    raise UnsupportedPluginTypeException("Module '%s' could not be instantiated'" % pluginName, ex)
ivy.exceptions.exceptions.UnsupportedPluginTypeException: (u"Module 'hide.plugins.load_beam_profile' could not be instantiated'", ValueError(u"Coordinate frame barycentricmeanecliptic not in allowed values ['altaz', 'barycentrictrueecliptic', 'cirs', 'fk4', 'fk4noeterms', 'fk5', 'galactic', 'galacticlsr', 'galactocentric', 'gcrs', 'geocentrictrueecliptic', 'hcrs', 'heliocentrictrueecliptic', 'icrs', 'itrs', 'lsr', 'precessedgeocentric', 'supergalactic']",))

**Comment by itachi-gf** [comment]
I am using Ubuntu 22.04 and Python version 2.7 in my environment.May I ask how you installed and ran the package? After following the installation instructions in the documentation, when I run the command "hide --strategy-start=2016-03-21-00:00:00 --strategy-end=2016-03-21-23:59:00 --verbose=True hide.config.bleien7m", it prompts me with "Command 'hide' not found, did you mean..." and suggests alternative commands.

**Comment by itachi-gf** [comment]
> When I run the command
> 
> ```
> hide --strategy-start=2016-03-21-00:00:00 --strategy-end=2016-03-21-23:59:00 --verbose=True hide.config.bleien7m
> ```
> 
> **There was an error，**
> 
> ```
> Traceback (most recent call last):
>   File "/home/zhangyazhou/.local/bin/hide", line 11, in <module>
>     load_entry_point('hide==0.1.0', 'console_scripts', 'hide')()
>   File "/home/zhangyazhou/anaconda3/envs/hide_env/lib/python2.7/site-packages/ivy/cli/main.py", line 28, in run
>     _main(*sys.argv[1:])
>   File "/home/zhangyazhou/anaconda3/envs/hide_env/lib/python2.7/site-packages/ivy/cli/main.py", line 37, in _main
>     mgr.launch()
>   File "/home/zhangyazhou/anaconda3/envs/hide_env/lib/python2.7/site-packages/ivy/workflow_manager.py", line 107, in launch
>     executor.run(ctx().params.plugins)
>   File "/home/zhangyazhou/anaconda3/envs/hide_env/lib/python2.7/site-packages/ivy/backend.py", line 48, in run
>     return map(LoopWrapper(loop), mapPlugin.getWorkload())
>   File "/home/zhangyazhou/anaconda3/envs/hide_env/lib/python2.7/site-packages/ivy/backend.py", line 126, in __call__
>     for plugin in self.loop:
>   File "/home/zhangyazhou/anaconda3/envs/hide_env/lib/python2.7/site-packages/ivy/loop.py", line 95, in next
>     return self._instantiate(plugin)
>   File "/home/zhangyazhou/anaconda3/envs/hide_env/lib/python2.7/site-packages/ivy/loop.py", line 136, in _instantiate
>     return PluginFactory.createInstance(pluginName, self.ctx)
>   File "/home/zhangyazhou/anaconda3/envs/hide_env/lib/python2.7/site-packages/ivy/plugin/plugin_factory.py", line 59, in createInstance
>     raise UnsupportedPluginTypeException("Module '%s' could not be instantiated'" % pluginName, ex)ivy.exceptions.exceptions.UnsupportedPluginTypeException: (u"Module 'hide.plugins.load_beam_profile' could not be instantiated'", ValueError(u"Coordinate frame barycentricmeanecliptic not in allowed values ['altaz', 'barycentrictrueecliptic', 'cirs', 'fk4', 'fk4noeterms', 'fk5', 'galactic', 'galacticlsr', 'galactocentric', 'gcrs', 'geocentrictrueecliptic', 'hcrs', 'heliocentrictrueecliptic', 'icrs', 'itrs', 'lsr', 'precessedgeocentric', 'supergalactic']",))
> ```
> 
> * My operating system is the virtual machine ubuntu20
>   Thank you a lot

I am using Ubuntu 22.04 and Python version 2.7 in my environment.May I ask how you installed and ran the package? After following the installation instructions in the documentation, when I run the command "hide --strategy-start=2016-03-21-00:00:00 --strategy-end=2016-03-21-23:59:00 --verbose=True hide.config.bleien7m", it prompts me with "Command 'hide' not found, did you mean..." and suggests alternative commands.

**Comment by abhinavn17** [comment]
This error is due to incorrect version of the healpy package. In my testing, I used a conda env with python 2.7 and healpy version 1.13.0 and that seems to resolve this error.
